variables:
  msbuild: 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe'

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy
  
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - vcpkg install --triplet=x64-windows
    - ./build.ps1
  tags:
    - windows
  artifacts:
    paths:
      - builds/Release/*

test-job:
  stage: test
  script:
    - Write-Host "Running Unit Tests!"
  tags:
    - windows

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - Write-Host "Deploying application..."
    - Write-Host "Application successfully deployed."
  tags:
    - windows

