/* This file was generated by syncqt. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H

#define QTWIDGETS_VERSION_STR "6.7.2"

#define QTWIDGETS_VERSION 0x060702

#endif // QT_QTWIDGETS_VERSION_H
