// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200630.5

void* winrt_make_EditorWinUI_MainPage()
{
    return winrt::detach_abi(winrt::make<winrt::EditorWinUI::factory_implementation::MainPage>());
}
WINRT_EXPORT namespace winrt::EditorWinUI
{
    MainPage::MainPage() :
        MainPage(make<EditorWinUI::implementation::MainPage>())
    {
    }
}
